#Moves csv files generated by BayeSSC, merges data, and build obs file
#Change numbers in lines 29-37 to match emperical data to be simulated, see https://github.com/UH-Bioinformatics/hBayeSSC for descriptions
dir<- setwd("./")

list_dir<- dir(,pattern = '_folder')

#moving all csv files to the same folder
for (i in 1:length(list_dir)){
  dir2<-setwd(paste(dir,"/",list_dir[i], sep=""))
  list_dir2<- list.dirs(path = ".", full.names = TRUE, recursive = TRUE)
  for (j in 2:length(list_dir2)){
  list_dir3<-list.files(paste(list_dir2[j], sep="" ),pattern = '.csv');  
  file.copy(from= paste(list_dir2,"/",list_dir3, sep=""), to=paste(dir,"/",list_dir[i],  sep=""), recursive=TRUE )
  }
#merging data
  
  filenames<-list.files(,pattern = '_stat.csv');
  rep<-sub(".*Rep(\\d+).*","\\1",filenames,perl=T)
  
  for( repn in unique(rep)){
    files=filenames[which(rep==repn)]
  datalist <- lapply(files, function(x){read.csv(file=x,header=T)})
  myfulldata <- do.call("rbind", datalist)
# building the obs file  
  temp_matrix<-  matrix(,nrow = dim(myfulldata)[1], ncol = 16)
  colnames(temp_matrix)<- c("species", "nsam", "nsites", "tstv", "gamma", "gen", "locuslow","locushigh",
                            "Nelow","Nehigh", "SegSites", "nucdiv", "Haptypes", "HapDiver", "TajimasD", "F*" )
  temp_matrix[1:dim(myfulldata)[1],"species"] <- c(paste("SP", seq(1,dim(myfulldata)[1]), sep=''))
  temp_matrix[1:dim(myfulldata)[1],"nsam"] <- rep(40,dim(myfulldata)[1])
  temp_matrix[1:dim(myfulldata)[1],"nsites"] <- rep(800,dim(myfulldata)[1])
  temp_matrix[1: dim(myfulldata)[1],"tstv"] <- rep(1,dim(myfulldata)[1])
  temp_matrix[1: dim(myfulldata)[1],"gamma"] <- rep(0,dim(myfulldata)[1])
  temp_matrix[1:dim(myfulldata)[1],"gen"] <- rep(1,dim(myfulldata)[1])
  temp_matrix[1:dim(myfulldata)[1],"locuslow"] <- rep (0.00008, dim(myfulldata)[1])
  temp_matrix[1:dim(myfulldata)[1],"locushigh"] <- rep (0.00008, dim(myfulldata)[1])
  temp_matrix[1:dim(myfulldata)[1],"Nelow"] <- rep( "500000", dim(myfulldata)[1])
  temp_matrix[1:dim(myfulldata)[1],"Nehigh"] <- rep( "500000", dim(myfulldata)[1])
  temp_matrix[1:dim(myfulldata)[1],"SegSites"] <-myfulldata$SegSites
  temp_matrix[1:dim(myfulldata)[1],"nucdiv"] <- myfulldata$NucltdDiv
  temp_matrix[1:dim(myfulldata)[1],"Haptypes"] <- myfulldata$Haptypes
  temp_matrix[1:dim(myfulldata)[1],"HapDiver"] <- myfulldata$HapDiver
  temp_matrix[1:dim(myfulldata)[1],"TajimasD"] <- myfulldata$TajimasD
  temp_matrix[1:dim(myfulldata)[1],"F*"] <- myfulldata$F.
  file_name<- sub(pattern = "SP(\\d+)_stat.csv", "obs_file", files[1])
  file_name<- sub(pattern = "./", paste("", sep=""), file_name)
  write.table(temp_matrix, file= file_name, quote= FALSE, sep = '\t',row.names = F)
  }
  setwd(dir)
  }  
  

  

    
    
    
    